language: nix
nix: 2.3.7
os: linux
dist: bionic

cache:
  directories:
    - /nix/store

script:
  - |
    nix-build \
      --argstr gitDescribe $(git describe)   \
      release.nix

# See https://github.com/travis-ci/travis-ci/issues/8667
install: true

deploy:
  provider: releases
  token:
    secure: e7wDYML+8np2fd8Wa+tXhNwEfw1mXKWYYh8XT/tjNgD1oWVCvam4sY7EyTbYnP7PUo0ehI7X0jH2bp289WQButxHO0EHDHfC2yiKSwfndUAttBW+20JqLqvH++tJ8NyaZZ/uYxZV+2EYd/sOjzYwgE2mne46tlkHumZLSiNt7bWLsIbOzgka9sllURhxBLWaL8iMtbtcbchrAOfeTDZPdayTm/nl6ew2phCXk9/kUDA5bkDlyDOFqSiUWerVs3wOvOqLWkl3MXgkJuTxmW0YiqPa9mOUuk85M7Wb0cJuxJckhS3e0R7dZRV9pAwY/A1cXu/zqBCM2K0K6fSxQpAz0HQowu1F0AOY1tmiPA3YK1A0zhQ3qWtzdZCPgh2EQgy9ml1+Np4bE5Alu5ZEqRH19ZKceLxhB3lhFaL9utxe5qKkiTULf4ost4mD0LsT4f6GPzm2xFCUxKjjpI0RB+TXmOmP00SpGWsozLD3r1XYEqZMeWkr7bVhdOKsOqAAJ6SnVAu2NzUsViT5paPnJ4JusA4YQ+UJK1Hg3ENdVMJeUmlZTa60eJxJwVbkEtkoO7iZRkm1ePgenstzuFN175lp8ydUJP1Bk4gAdIHH7O1iMxVz9eznrgu4RKYV6fclUgt6fz+h/ClSEFKb/l9ScDgJUOuL6bfLvxj9NIn7WmwAprU=
  file_glob: true
  file:
    - result/*
  on:
    tags: true
  cleanup: false
  # Until dplv2
  skip_cleanup: true
